language: ruby

before_install:
  - gem install bundler
  - psql -c 'create database aleftng_test;' -U postgres
  - ls -la
  - cp config/travis_database.yml config/database.yml

before_script:
  - chmod u+x bin/rake
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake db:seed RAILS_ENV=test

services:
  - postgresql

addons:
  postgresql: "9.3"



rvm:
- 2.2.0

notifications:
  slack: tesateam:9X4eC8Kij8523YspIOSxIvyC

branches:
  only:
    - osicky_master
    - osicky_develop


