
stuba_ldap: &STUBA_LDAP
  host: ldap.stuba.sk
  port: 636
  attribute: uid
  base: ou=People,dc=stuba,dc=sk
  ssl: simple_tls

stuba_ldap2: &STUBA_LDAP2
   host: ldap2.stuba.sk
   port: 636
   attribute: uid
   base: ou=People,dc=stuba,dc=sk
   ssl: simple_tls

## Environment
development:
-
  <<: *STUBA_LDAP # Use the VPN, Luke. Or local users.
-
  <<: *STUBA_LDAP2

test:
-
  <<: *STUBA_LDAP
-
  <<: *STUBA_LDAP2

sandbox:
-
  <<: *STUBA_LDAP
-
  <<: *STUBA_LDAP2

staging:
-
  <<: *STUBA_LDAP
-
  <<: *STUBA_LDAP2

production:
-
  <<: *STUBA_LDAP
-
  <<: *STUBA_LDAP2
